"""German labels used by validation and report presentation."""

FIELD_LABELS = {
    "merchant": "Anbieter",
    "invoice_number": "Rechnungsnummer",
    "invoice_date": "Rechnungsdatum",
    "service_start": "Beginn des Leistungszeitraums",
    "service_end": "Ende des Leistungszeitraums",
    "overnight_count": "Übernachtungen",
    "room_count": "Zimmeranzahl",
    "transport_mode": "Verkehrsmittel",
    "distance_km": "Entfernung",
    "origin": "Abfahrt / Abflug",
    "destination": "Ziel",
    "flight_number": "Flugnummer",
    "category": "Kategorie",
    "currency": "Währung",
    "total": "Gesamtbetrag",
    "net_total": "Nettosumme",
    "tax_total": "Steuersumme",
    "breakfast_total": "Frühstücksbetrag",
    "breakfast_net": "Frühstück netto",
    "breakfast_tax": "Frühstücksteuer",
    "net": "Nettobetrag",
    "tax": "Steuerbetrag",
    "gross": "Bruttobetrag",
}
